name: Build & Deploy LaTeX Document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: overleaf/github-latex-ci@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true

      - name: Setup Output Directory
        run: |
          mkdir output
          mv index.html output/
          mv Fares_Khalil_Resume.pdf output/

      - name: Commit PDF to main
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: main
          folder: output
          clean-exclude: |
            .nojekyll
